# Generated by Django 6.0.4 on 2026-05-02 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("face_detection", "Face detection"),
                            ("face_recognition", "Face recognition"),
                            ("person_detection", "Person detection"),
                            ("person_segmentation", "Person segmentation"),
                            ("pose_estimation", "Pose estimation"),
                            ("tracker", "Tracker"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("license", models.CharField(max_length=64)),
                ("source_url", models.URLField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("pretrained", "Pretrained (upstream weights)"),
                            ("fine_tuned", "Fine-tuned"),
                            ("trained_local", "Trained locally"),
                        ],
                        default="pretrained",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["family", "name", "-registered_at"],
                "unique_together": {("name", "version")},
            },
        ),
    ]
