# Generated by Django 6.0.4 on 2026-05-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allowlist", "0002_enrollmentimage_status_faceembedding"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("timestamp_seconds", models.FloatField()),
                ("x", models.PositiveIntegerField()),
                ("y", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("score", models.FloatField()),
                ("similarity", models.FloatField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("unknown", "Unknown — blur"),
                            ("uncertain", "Uncertain — blur + flag"),
                            ("conflict", "Identity conflict — blur + flag"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="projects.analysisjob",
                    ),
                ),
                (
                    "matched_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="allowlist.allowedperson",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "frame_index"],
                        name="projects_fa_job_id_ee70fc_idx",
                    )
                ],
            },
        ),
    ]
