# Generated by Django 6.0.4 on 2026-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_job_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="style",
            field=models.CharField(
                choices=[
                    ("mosaic", "Mosaic"),
                    ("gaussian", "Gaussian blur"),
                    ("solid", "Solid fill"),
                    ("eye_bar", "Eye bar"),
                ],
                default="mosaic",
                max_length=16,
            ),
        ),
    ]
