# Generated by Django 6.0.4 on 2026-05-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_exportjob_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportjob",
            name="kind",
        ),
    ]
