# Generated by Django 6.0.4 on 2026-05-02 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allowlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentimage",
            name="status",
            field=models.CharField(
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                default="accepted",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=64)),
                ("model_version", models.CharField(max_length=64)),
                ("vector", models.BinaryField()),
                ("dim", models.PositiveIntegerField()),
                ("detector_score", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="allowlist.enrollmentimage",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="allowlist.allowedperson",
                    ),
                ),
            ],
        ),
    ]
